### PR TITLE
Change Application ID 

### PR DESCRIPTION
**Pull request by scx**
New Application ID: `io.github.wxmaxima_developers.wxMaxima`

This is related to [submitting](https://github.com/flathub/flathub/pull/801) my flatpak package to the Flathub repository.

See also:
https://github.com/wxMaxima-developers/wxmaxima/pull/1074
https://github.com/wxMaxima-developers/wxmaxima/issues/1073

### CODE REVIEW

**Comment by scx** [comment]
As I said before, changing the ID may be a bit [problematic](https://github.com/wxMaxima-developers/wxmaxima/pull/1074#issuecomment-450583181). For this reason, I would ask you to look at the submitted commits (especially the [first one](https://github.com/scx/wxmaxima/commit/459705dfe47810609f7c753d82d2b98775d8bcc9)) before you merge them.

**Comment by gunterkoenigsmann** [comment]
As the ID isn't used by the application (on Linux if you open 2 files that produces 2 wxMaxima processes which uses up about 50 Megabytes more than opening the worksheets from the same process but means if one process crashes the other worksheet will still work) it can be changed freely.

**Comment by gunterkoenigsmann** [comment]
Ok... ...a few reboots later it works again => wxMaxima is one of the first applications adhering to the new standard => Thanks a lot, again,
  Gunter.

**Comment by scx** [comment]
@gunterkoenigsmann 

> I actually like this behaviour but - do you know what we might have overlooked? I guess the change in behaviour isn't intended...

Sorry, but I have no idea.
BTW, I have already updated my [flatpak](https://github.com/scx/wxmaxima-flatpak/commit/b259cb1708956a109c0f3a5491031e4211f83f38) package to the latest version (*19.01.0*).
This also applies to my [COPR](https://copr.fedorainfracloud.org/coprs/scx/wxMaxima/build/846222/) repository.

**Pull request merged**
