### PR TITLE
Feature/speedup 1

### PR DESCRIPTION
**Pull request by KubaO**
More performance improvements. Those were sitting around in my queue for a while now. Nothing breathtaking, but incremental.

### CODE REVIEW

**Comment by gunterkoenigsmann** [comment]
Looks great!
But doesn't yet compile on Travis.  Would you be so kind and add a commit that fixes this? As soon as it compiles I will hit the "merge" button.

**Comment by KubaO** [comment]
I'll submit a fix for the missing include.

**Comment by gunterkoenigsmann** [comment]
I didn't know that in git you can use hierarchical branch names. 
I normally hope that the tests travis runs are enough to test for all weird things - and most things that can go wrong immediately crash the program/garble the display/make maxima misbehave on executing the first command.

---

additionally to the missing vector.h that produced a scary number of error messages (at least if using a mobile phone for viewing the travis log) I get one error for as_const which was introduced in C++17 only.
````
/home/gunter/wxmaxima-kuba/src/main.cpp: In member function ‘void MyApp::OnFileMenu(wxCommandEvent&)’:
/home/gunter/wxmaxima-kuba/src/main.cpp:487:33: error: ‘as_const’ is not a member of ‘std’; did you mean ‘is_const’?
  487 |       for (wxMaxima *win : std::as_const(m_topLevelWindows))
      |                                 ^~~~~~~~
      |                                 is_const
make[2]: *** [src/CMakeFiles/wxmaxima.dir/build.make:1116: src/CMakeFiles/wxmaxima.dir/main.cpp.o] Error 1
````

**Comment by gunterkoenigsmann** [comment]
If I just remove the construct C++11 still doesn't provide wxMaxima seems to work fine for the files I am currently working on.

I am already curious how fast we will manage to make this program...

**Comment by KubaO** [comment]
Re git: Check out smartgit. It's free for open source work, and is an excellent piece of software. Personally, I'd not be using git without it.

**Pull request merged**
