### PR TITLE
Typofix

### PR DESCRIPTION
**Pull request by richardgobeli**

### CODE REVIEW

**Comment by gunterkoenigsmann** [comment]
Thanks a lot! Seems I caused a conflict - but that was easy to resolve.

**Comment by richardgobeli** [comment]
I don't know how to resolve the error in verification.  The text is the same. It is just shifted by one word.

**Comment by yurchor** [comment]
Is it possible to unerase purged manual translations (German and Ukrainian)?

Thanks in advance for your answer.

**Comment by gunterkoenigsmann** [comment]
The error in verification was caused by me - and was easy to fix.

Unerasing should be easy as git stores the whole history so one can always go back in time. What did I delete I shouldn't have to?

**Comment by yurchor** [comment]
> What did I delete I shouldn't have to?

Whole German and Ukrainian manual translations.

**Comment by yurchor** [comment]
> How did I cause that?
> Give me a few hours. But I will repair that, too.

No harm was done (I have a backup). Just wanted to know if I should recommit the translation and wanted the German colleagues to be acknowledged. Thanks for your efforts, anyway.

**Comment by yurchor** [comment]
> If you could do so I would be quite thankful.

Done. ;)

**Comment by gunterkoenigsmann** [comment]
I think I have found the bug that allowed me to easily loose translations. Hope I didn't trigger the problem another time whilst trying to fix it.

**Comment by gunterkoenigsmann** [comment]
Wait: You don't mean I have purged the .po file's contents but the translation of the .md and .html files? I think then there is a bug in CMakeLists.txt. Will search for that the day after tomorrow, most probably.

**Pull request closed without merging**
